website/music/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail' ),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

website/music/models.py
from django.db import models

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=100)
    genre= models.CharField(max_length=100)
    album_logo = models.CharField(max_length=100)

    def __str__(self):
        return self.artist + "-" + self.album_title

class Song(models.Model):
    album= models.ForeignKey(Album, on_delete= models.CASCADE)
    file_type= models.CharField(max_length=100)
    song_title= models.CharField(max_length=100)

    def __str__(self):
        return self.song_title

website/music/views.py
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from .models import Album


# Create your views here.

def index(request):
    all_album= Album.objects.all()
    context= {'all_album': all_album}
    return render(request, 'music/index.html', context,)

def detail(request, album_id):

    album = get_object_or_404(Album, pk=album_id)

    # try:
    #     album = Album.objects.get(pk=album_id)
    # except Album.DoesNotExist:
    #     raise Http404("Does not exist")

    return render(request, 'music/detail.html', {'album':album})

website/music/templates/music/detail.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

<ul>

    {% for song in album.song_set.all %}
    <li>{{ song.song_title }} - {{ song.file_type }}</li>
    {% endfor %}


</ul>

website/music/templates/music/index.html
{% if all_album %}
    <ul>
        {% for album in all_album %}
        <li><a href="{% url 'detail' album.id %}">{{album.album_title }}</a></li>
        {% endfor %}
    </ul>

{% endif %}